export default {
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'Forgot Password',

  DIRECCIONESMODAL: 'DireccionesModal',

  HOMENAV: 'HomeNav',
  HOME: 'Home',
  HOME_TAB: 'HomeTab',
  PERFIL_NAVIGATION: 'PerfilNavigation',
  PERFIL: 'Perfil',
  PERFIL_EDITAR: 'PERFIL_EDITAR',
  PERFILPRESTADORHOME: 'PerfilPrestadorHome',
  ORDENSERVICIOMODAL: 'OrdenServicioModal',
  CREARORDENSERVICIOMODAL: 'CrearOrdenServicioModal',
  SERVICIOSMODAL: 'ServiciosModal',

  ORDENESSERVICIO_NAVIGATION: 'OrdenesServicioNav',
  ORDENESSERVICIOACTIVAS: 'OrdenesServicioActivas',
  ORDENESERVICIO_ACTIVA_MODAL: 'OrdenServicioActivaModal',
  ORDENESERVICIO_HISTORIAL_MODAL: 'OrdenServicioHistorialModal',
  ORDENESERVICIO_HISTORIAL_ITEM_MODAL: 'OrdenServicioHistorialItemModal',
  ORDENESERVICIO_CANCELAR: 'OrdenServicioCancelar',
  ORDENESERVICIO_REPORTE: 'OrdenServicioReporte',

  MAPMODAL: 'MapModal',
  FirstDirection: 'FirstDirection',
  REGISTER_EMPLEADOR: 'RegisterEmpleador',
  REGISTER_PRESTADOR: 'RegisterPrestador',

  CHAT_NAVIGATION: 'ChatNavigation',
  CHAT_ID: 'Chat ID',
  CHATS: 'Chats',
  PRESTADOR_CHAT_ID: 'PRESTADOR_ChatID',
  PRESTADOR_CHATS: 'PRESTADOR_Chats',

  PRESTADOR_HOMETAB: 'PrestadorHomeTab',
  PRESTADOR_HOMENAV: 'PrestadorHomeNav',
  PRESTADOR_HOME: 'PrestadorHome',
  PRESTADOR_MAPMODAL: 'PrestadorMapModal',
  PRESTADOR_CHAT_NAVIGATION: 'PrestadorChatNavigation',
  PRESTADOR_CHATS: 'PrestadorChats',
  PRESTADOR_CHATS_ID: 'PrestadorChatID',
  PRESTADOR_PERFIL_NAVIGATION: 'PerfilPrestadorNavigation',
  PRESTADOR_PERFIL: 'PrestadorPerfil',
  PRESTADOR_MODALORDENSERVICIOMODAL: 'PrestadorModalOrdenServicioModal',
  PRESTADOR_CALENDARIO: 'CALENDARIO',
  PRESTADOR_REPORTE: 'PrestadorReporte',
  PRESTADOR_CANCELAR: 'PrestadorCancelar',

  PRESTADOR_ORDENESTERMINADAS: 'PrestadorOrdenesTerminadas',
  PRESTADOR_ORDENESSERVICIOACTIVAS: 'OrdenesServicioActivas',
  PRESTADOR_ORDENESERVICIO_ACTIVA_MODAL: 'OrdenServicioActivaModal',
  PRESTADOR_ORDENESERVICIO_HISTORIAL_MODAL: 'OrdenServicioHistorialModal',
  PRESTADOR_ORDENESERVICIO_HISTORIAL_ITEM_MODAL:
    'OrdenServicioHistorialItemModal',
}
